[project]
name = "optical-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cupy-cuda13x>=13.6.0",
    "opencv-python>=4.13.0.92",
]

[dependency-groups]
dev = [
    "ruff>=0.15.1",
]
