line-length = 120
indent-width = 2

exclude = [
    ".venv",
    ".vscode",
    ".git",
    ".ruff_cache",
    "build"
]

target-version = "py313"

[lint]
select = ["E", "W", "F", "I", "B"]

[format]
quote-style = "single"
indent-style = "space"
line-ending = "lf"
